- Maddori.Apple-Server/app.js
- Maddori.Apple-Server/models/reflection.js
- Maddori.Apple-Server/models/team.js
- Maddori.Apple-Server/routes/feedbacks/index.js
- Maddori.Apple-Server/routes/reflections/index.js
- Maddori.Apple-Server/routes/teams/index.js
- Maddori.Apple-Server/routes/teams/teams.js
- Maddori.Apple-Server/routes/users/index.js
- Maddori.Apple-Server/routes/users/users.js
Setup 페이지에서 활용하는 유저 등록, 팀 합류, 팀 탈퇴, 팀 등록 api를 구현하였습니다.
1. 클라이언트는 URI(/users/login 등)를 사용해 서버로 request를 보내게 됩니다.
2. 서버는 위 URI를 바탕으로 request를 분류하게 됩니다. (**app.js 파일**)
``` javascript
//{주소}/users/ 로 시작하는 모든 요청은 routes 폴더 내의 users 폴더 내의 index 파일에서 처리해줘!
app.use('/users', require('./routes/users/index'));
//{주소}/teams/ 로 시작하는 모든 요청은 routes 폴더 내의 teams 폴더 내의 index 파일에서 처리해줘!
app.use('/teams', require('./routes/teams/index'));
```
3. 위에서 분류된 request는 index 파일에서 최종적으로 분류됩니다.
클라이언트가 /users 로 시작하는 request를 보냈다고 가정하고, 그 request가 분류된 routes/users/index 파일을 살펴보면 아래와 같이 해석할 수 있습니다.
``` javascript
//POST {주소}/users/login 요청은 userLogin 함수에서 수행해줘!
router.post('/login', userLogin);
//POST {주소}/users/join-team 요청은 userJoinTeam 함수에서 수행해줘!
router.post('/join-team', userJoinTeam);
//DELETE …
```
> [FEAT] Setup 페이지 api 구현 - 유저 등록, 팀 합류, 팀 탈퇴, 팀 등록

- Maddori.Apple-Server/routes/feedbacks/feedbacks.js
- Maddori.Apple-Server/routes/feedbacks/index.js
- Maddori.Apple-Server/routes/teams/index.js
- Maddori.Apple-Server/routes/teams/teams.js
AddFeedback~ View(AddFeedbackMember, AddFeedbackContent)에서 사용하는 팀 멤버 가져오기, 피드백 추가하기 api를 구현하였습니다.
AddFeedbackMember View에서 팀에 속한 멤버 리스트를 가져올 수 있고, AddFeedbackContent에서 피드백을 받는 사람, 피드백 내용을 작성해 피드백 추가하기를 진행할 수 있습니다.
- 팀에 속한 멤버 가져오기
team_id를 받아 id가 일치하는 팀이 있다면, userteam테이블과 user 테이블 JOIN을 수행해 해당 팀에 속한 유저의 id와 username 리스트를 반환합니다.
- 새로운 피드백 추가하기
피드백을 받는 사람의 user_id와, 피드백 내용을 req.body를 통해 받게 되고, feedback 테이블에 새로운 feedback을 추가하여 추가된 feedback을 반환합니다.
- **팀에 속한 멤버 가져오기**
URI : GET `/teams/{team_id}/members`
request header : { "user_id" : "1" }
- **새로운 피드백 추가하기**
URI : POST `/teams/{team_id}/reflections/{reflection_id}/feedbacks`
request header : { "user_id" : "1" }
request body :
```json
{
"type" : "Continue",
"keyword" : "서버2",
"content": "서버 테스트입니다2",
"start_content": "시작합니다2",
"to_id": "2"
} …
```
> [FEAT] AddFeedback View api 구현 - 팀 멤버 정보, 피드백 추가

- Maddori.Apple-Server/routes/feedbacks/feedbacks.js
- Maddori.Apple-Server/routes/reflections/reflections.js
- Maddori.Apple-Server/routes/teams/teams.js
- Maddori.Apple-Server/routes/users/users.js
기존의 status code 500은 서버 쪽 에러를, status code 400은 클라이언트 쪽 에러를 의미합니다.
형식이 안 맞는 경우에도 클라이언트에서는 서버 에러라는 response를 받아 혼돈이 있을 수 있기에 status code 수정합니다.
_기능 변경이 없는 간단한 코드 변경이므로 따로 리뷰 요청은 하지 않겠습니다._
에러 발생 http status code 400으로 일괄 변경
추후에 서버, 클라이언트 에러 구분하여 코드 변경할 예정입니다.
- close #23
> [CHORE] 에러 발생 http status code 400으로 변경

- Maddori.Apple-Server/models/feedback.js
즐겨찾기 기능을 삭제했기 때문에 is_favorite 필드가 불필요해졌습니다. 따라서 is_favorite 필드를 삭제합니다.
feedback 테이블의 is_favorite 필드 삭제
테이블 설정을 변경했기 때문에, 데이터베이스에서 기존 테이블을 삭제 후 서버를 재실행해줘야 변경된 설정대로 테이블이 다시 생성됩니다.
- close #25
> [CHORE] feedback 테이블 is_favorite 필드 삭제

- Maddori.Apple-Server/routes/feedbacks/feedbacks.js
- Maddori.Apple-Server/routes/feedbacks/index.js
1. EditFeedbackFromMe View - Feedback 수정 API를 구현
- 현재 진행중인 회고에 대한 예외처리는 Middleware를 통해서 구현한다.
- update 후 data를 return 했을 때, JSON으로 return이 안되서, PK로 조회한 후 return => 리팩토링 방법에 대해 연구 필요
2. FeedbackFromMeDetail View - Feedback 삭제 API를 구현
- 삭제 API의 경우, detail에 data를 따로 담아두지 않았는데, 필요한 경우에 추가하겠습니다.
- Postman을 이용하여, API Test
- 요청 URI(수정, 삭제 API 모두)
http://localhost:3000/teams/1/reflections/1/feedbacks/12
- 수정 API Request Body
```
{
"type": "Stop",
"keyword": "s",
"content": "바꾸기 성공?1",
"start_content": "시작하기"
}
```
- close #33
> [FEAT] EditFeedbackFromMe, FeedbackFromMeDetail View - Feedback 수정, 삭제 API 구현

- Maddori.Apple-Server/app.js
- Maddori.Apple-Server/routes/feedbacks/index.js
URI slash 추가, getTeamAndUserFeedback에 미들웨어 적용
URI slash 추가, getTeamAndUserFeedback에 미들웨어 적용
- close #22
> [CHORE] URI slash 추가, getTeamAndUserFeedback에 미들웨어 적용

- Maddori.Apple-Server/routes/feedbacks/feedbacks.js
- Maddori.Apple-Server/routes/reflections/reflections.js
- Maddori.Apple-Server/routes/teams/teams.js
- Maddori.Apple-Server/routes/users/users.js
1. response에서 int형이 string으로 반환되는 에러
2. detail이 아닌 data로 정의되어 반환되는 에러
response 형식 오류는 클라이언트 연결 작업에 영향을 줄 수 있기에 우선적으로 처리했습니다.
1. response에서 int형이 string으로 반환되는 에러 수정
2. detail이 아닌 data로 정의되어 반환되는 에러 수정
리팩토링 과정에서 response 형식을 좀 정리하면 좋을 것 같다는 생각이 들었습니다.
struct 형식으로 response 모델을 만들어두고, 전체적으로 통일된 response 형식을 만들어봅시다
🍎 클라 연결이 바로 들어갈 것 같아서 ASAP 이슈이기 때문에 코드리뷰 요청 없이 pr 머지하겠습니다!
- close #44
> [BUG] response 형식 오류 수정

- Maddori.Apple-Server/routes/users/users.js
userLogin api에서 detail이 아닌 datail로 response가 보내지고 있어서 오타 수정합니다.
오타 수정
간단한 오타 수정이기에 리뷰 요청 하지 않겠습니다!
- close #
> [CHORE] datail을 detail로 오타 수정(#48)

- Maddori.Apple-Server/routes/reflections/index.js
- Maddori.Apple-Server/routes/reflections/reflections.js
- State가 "Done"인 reflection이 아닌 모든 reflection을 조회함.
- reflection 조회 query에 state가 "Done"인 data만 가져오도록 수정.
GET http://localhost:3000/api/v1/teams/1/reflections
- close #57
> [BugFix] : getPastReflectionList API 수정

- Maddori.Apple-Server/routes/feedbacks/feedbacks.js
현재 feedback id를 얻을 수 없어서 피드백 삭제 요청을 보낼 수 없습니다. 이에 getCertainTypeFeedbackAll에서 feedback id를 반환합니다.
response field에 feedback id 추가
getCertainTypeFeedbackAll api 실행
매우 간단한 코드 수정이기 때문에 리뷰 없이 머지합니다!
- close #
> [CHORE] getCertainTypeFeedbackAll 의 response data에 feedback id 추가

- Maddori.Apple-Server/.idea/.gitignore
- Maddori.Apple-Server/routes/feedbacks/feedbacks.js
- Maddori.Apple-Server/routes/feedbacks/index.js
- Maddori.Apple-Server/routes/reflections/index.js
- createFeedback, updateFeedback, deleteFeedback의 bugfix
- 피드백 수정 API에서 data의 type 혹은 값이 잘못 된 경우 400 Error를 반환하는 로직 추가.
- 피드백 삭제 API에 미들웨어 추가
- 피드백 삭제 APId에서
1. 본인이 작성한 피드백이 아니어도 삭제
2. 피드백이 존재하지 않아도 요청이 성공적으로 수행됨
위 2가지 API에 대한 요청 처리 추가
- 피드백 생성, 수정 API에서 feedback의 type은 “Continue”, “Stop” 둘 중 하나의 값만 가질 수 있음. 따라서, 이 type이 요청으로 들어오지 않을 경우 400 에러 반환
- 요청 단에서 처리하는 다른 API에서도 많이 사용될 것 같은 로직은 미들웨어로 빼는 것이 좋을 것 같습니다.
- express-validator를 활용하는 방법도 있을 것 같습니다.
- close #63
> [BugFix] : Feedback 관련 API 수정

- Maddori.Apple-Server/routes/teams/teams.js
서버에서 통일된 MemberResponse 형식을 사용하기 위해 response 형식을 수정합니다.
기존에는 member 객체 user_id로 응답 -> id로 응답하도록 변경
getTeamMembers api 실행
ASAP입니다! 코드 리뷰 없이 머지합니당
- close #
> [CHORE] getTeamMembers response 형식 수정

- Maddori.Apple-Server/middlewares/auth.js
- Maddori.Apple-Server/middlewares/validate.js
- Maddori.Apple-Server/package-lock.json
- Maddori.Apple-Server/package.json
- Maddori.Apple-Server/routes/auth/auth.js
- Maddori.Apple-Server/routes/feedbacks/feedbacks.js
- Maddori.Apple-Server/routes/feedbacks/index.js
- Maddori.Apple-Server/routes/reflections/index.js
- Maddori.Apple-Server/routes/reflections/reflections.js
- Maddori.Apple-Server/routes/teams/index.js
- Maddori.Apple-Server/routes/teams/teams.js
- Maddori.Apple-Server/routes/users/index.js
- Maddori.Apple-Server/routes/users/users.js
- 서비스의 사용자 입력 데이터의 제한에 관계 없이 모든 요청이 들어가서, 제한이 필요함.
- feedback request body validation code 추가
1. feedback 수정 API
PUT http://localhost:3000/api/v1/teams/1/reflections/1/feedbacks/1
2. feedback 생성 API
POST http://localhost:3000/api/v1/teams/1/reflections/1/feedbacks
- close #72
> [BugFix] 사용자 입력 제한

- Maddori.Apple-Server/config/config.js
서버 로그를 찍어보니 아래와 같은 에러가 계속 나와서 useUTC 설정 때문인 것 같아 해당 설정 삭제합니다.
해당 에러가 기능에 영향을 주는 것은 아니지만 일단 수정합니다.
- close #
> [FIX] sequelize config 에러 해결

- Maddori.Apple-Server/middlewares/validate.js
- Maddori.Apple-Server/routes/feedbacks/feedbacks.js
- 현재 feedback start_content의 내용이 null이면 추가가 안되는 에러 발생
- 특정 멤버에게 작성한 피드백 가져오는 부분에서, 현재 회고가 아닌 저번 회고의 피드백을 가져옴
- close #
> [BUG] feedback 추가 에러 수정

- Maddori.Apple-Server/routes/reflections/index.js
- Maddori.Apple-Server/routes/reflections/reflections.js
현재 회고를 종료해도 recent_reflection_id 가 업데이트가 안 됨
- recent_reflection_id를 종료된 회고의 id로 설정해주는 코드 추가
- endInProgressReflection에서 회고 일정이 현재 시간을 지났는지 검증하는 미들웨어 추가 적용
- close #82
> [FIX] endInProgressReflection에서 recent_reflection_id 업데이트

- Maddori.Apple-Server/routes/auth/auth.js
클라쪽 요청으로 appleLogin response 형식 변경합니다.
appleLogin api 실행
user_id를 이렇게 반환해주는게 보안적으로 맞는지는 잘 모르겠네요..
- close #
> [CHORE] appleLogin 응답 형식 수정(user_id 반환 추가)

- Maddori.Apple-Server/routes/auth/auth.js
> [CHORE] appleLogin response 형식 변경

- Maddori.Apple-Server/.idea/.gitignore
- Maddori.Apple-Server/app.js
- Maddori.Apple-Server/bin/www
- Maddori.Apple-Server/config/config.js
- Maddori.Apple-Server/middlewares/auth.js
- Maddori.Apple-Server/middlewares/validate.js
- Maddori.Apple-Server/models/css.js
- Maddori.Apple-Server/models/feedback.js
- Maddori.Apple-Server/models/index.js
- Maddori.Apple-Server/models/reflection.js
- Maddori.Apple-Server/models/team.js
- Maddori.Apple-Server/models/user.js
- Maddori.Apple-Server/models/userteam.js
- Maddori.Apple-Server/models/usertoken.js
- Maddori.Apple-Server/package-lock.json
- Maddori.Apple-Server/package.json
- Maddori.Apple-Server/routes/auth/auth.js
- Maddori.Apple-Server/routes/auth/index.js
- Maddori.Apple-Server/routes/feedbacks/feedbacks.js
- Maddori.Apple-Server/routes/feedbacks/index.js
- Maddori.Apple-Server/routes/reflections/index.js
- Maddori.Apple-Server/routes/reflections/reflections.js
- Maddori.Apple-Server/routes/teams/index.js
- Maddori.Apple-Server/routes/teams/teams.js
- Maddori.Apple-Server/routes/users/index.js
- Maddori.Apple-Server/routes/users/users.js
- Maddori.Apple-Server/seeders/testData.js
- Maddori.Apple-Server/utils/jwt.util.js
release v1.2 배포 완료하였기 때문에 main 브랜치로 머지합니다.
이후 업데이트 기능 추가는 develop 브랜치를 기반으로 작업합니다.
main 브랜치로 머지
> [FEAT] Release/v1.2 배포 완료

- Maddori.Apple-Server/middlewares/validate.js
- Maddori.Apple-Server/models/feedback.js
- Maddori.Apple-Server/routes/feedbacks/feedbacks.js
- Maddori.Apple-Server/seeders/testData.js
피드백 포맷을 수정하였습니다 (start_content 삭제, content에 모든 내용 저장)
- model 파일 수정(feedback 테이블의 start_content 삭제, content의 글자 제한 수정)
- validate 미들웨어에서 start_content 값 검증 로직 제거
- createFeedback, updateFeedback, getFromMeToCertainMemberFeedbackAll 에서 start_content 관련 코드 제거
- seed 데이터(테스트 데이터)에서 start_content 필드 제거
createFeedback, updateFeedback, getFromMeToCertainMemberFeedbackAll, getCertainTypeFeedbackAll, getTeamAndUserFeedback 수행
- start_content 필드 없이 response가 옵니다
- feedback 테이블 변경 정보
- close #92
> [FEAT] 피드백 포맷 수정
