hwiwonK/MacC-Team-Maddori.Apple-Server

Maddori.Apple-Server/models/css.js, Maddori.Apple-Server/models/reflection.js, Maddori.Apple-Server/models/team.js, Maddori.Apple-Server/models/user.js, Maddori.Apple-Server/models/userteam.js
아래 erd 기준으로 데이터베이스를 구현했습니다
- 데이터베이스 생성
- 테이블 생성 (user, userteam, team, reflection, css)
- 테이블간 연관관계 설정 (외래키 설정)
- 테스트 해보고 싶으신게 있다면 찾아와주세요
- on delete : cascade 를 사용하였습니다
1:N 관계에 있는 테이블에서 1쪽의 데이터가 사라지면 N쪽의 데이터도 사라지게 하는 설정입니다.
ex) 팀 테이블에 있는 '맛사' 팀, 회고 테이블에 있는 맛사 팀이 진행 중인 '첫번째 스프린트' 가 있다면
'맛사' 팀 정보가 삭제되었을 때 '첫번째 스프린트' 데이터도 삭제되게 구현하였습니다.
일단 모든 1:N 관계를 가진 곳에서 설정을 부여하였는데, 아래와 같은 상황 때문에 어떤 부분에 이 설정을 부여하는게 좋을지 추후에 함께 논의해봐야할 것 같아요! ↓
🤔 지금은 유저 테이블(1) - css 테이블(N) 형태로 구현되어있는데, 이렇게 되면 유저가 삭제될 때 해당 유저가 작성한 css 내용도 함께 삭제되게 됩니다. 그럼 그 css를 받았던 유저는 더 이상 해당 css를 확인할 수 없게 돼요!
- null 허용
위에 스크린샷에서 Null : YES 라고 되어있는 부분은 Null 값을 허용하는 필드입니다!
제 기준으로 판단했을 때 Null 값이 있어도 되는 부분만 Null 값 허용 처리 해줬는데, 틀렸을 수도 있으니깐 혹시 틀린 부분 눈에 보이시면 알려주세요🥲
- close #7 
https://sequelize.org/docs/v7/core-concepts/assocs/
=> [FEAT] 데이터베이스 구현

Maddori.Apple-Server/models/feedback.js, Maddori.Apple-Server/models/reflection.js, Maddori.Apple-Server/models/team.js, Maddori.Apple-Server/models/user.js, Maddori.Apple-Server/models/userteam.js
테이블명 수정, on DELETE 옵션 수정, 모델 속성 수정 필요
- 테이블 css를 feedback으로 변경하였습니다.
- feedback의 from_id 외래키의 on DELETE 옵션을 SET NULL로 변경하였습니다.
어떤 사용자가 탈퇴했을 때 그 사용자가 쓴 피드백은 삭제되지 않고, from_id에는 NULL값이 들어갑니다.
어떤 사용자가 탈퇴했을 때 그 사용자가 받은 피드백은 삭제됩니다.
- 모델 속성 (charset, collate)을 수정하였습니다
레코드에 이모지를 허용하기 위해서는 charset은 utf8mb4, collate는 utf8mb4_general_ci로 변경해야 했습니다.
해당 속성을 적용하여 데이터베이스를 다시 생성하였고, model 폴더 내의 각 모델 정의 코드를 위를 반영해 수정하였습니다.
1. mysql 세팅 후 `create database maddori_apple default character set utf8mb4;` 로 데이터베이스를 생성합니다.
2. 서버와 위에서 만든 데이터 베이스 연결 후 npm run start를 수행하면 model 폴더 내에 정의된 내용에 따라 자동으로 테이블이 생성됩니다.
- close #9 
https://sequelize.org/docs/v6/core-concepts/assocs/
=> [FEAT] 데이터베이스 수정

Maddori.Apple-Server/routes/reflections/index.js, Maddori.Apple-Server/routes/reflections/reflections.js, Maddori.Apple-Server/routes/teams/index.js, Maddori.Apple-Server/routes/teams/teams.js
Home View에서 사용하는 팀 정보 가져오기, 현재 회고 정보 가져오기 api를 구현하였습니다.
메인 화면을 구성하는 데이터를 위 두 api를 통해 가져올 수 있습니다.
- 팀 정보 가져오기
team_id를 받아 id가 일치하는 팀이 있다면, team 테이블에서 데이터를 찾아 가져옵니다.
- 현재 회고 정보 가져오기
team_id를 받아 id가 일치하는 팀이 있다면, team의 현재 회고 id를 가져옵니다. 해당 회고 id를 사용해 회고의 전체 정보, 회고에 등록된 키워드 리스트를 가져오게 됩니다.
- **팀 정보 가져오기**
URI : GET `/teams/{team_id}`
request header : { "user_id" : "1" }
- **팀의 현재 회고 정보 가져오기**
URI : GET `/teams/{team_id}/reflections/current`
request header : { "user_id" : "1" }
- 요청을 보내는 유저가 실제로 요청 대상 팀에 속해있는 멤버인지 검증하는 미들웨어 구현 후 코드 추가할 예정입니다
- 팀 정보 가져오기 request는 오로지 한 번만 수행해도 되는 반면, 팀의 현재 회고 정보는 데이터 변경이 일어날 수 있기에 뷰가 appear 될 때마다 현재 회고 정보를 가져오는 request를 보내야 합니다.
따라서 팀 정보 가져오기 api와 팀 현재 회고 정보 가져오기 api를 구분했습니다. 혹시 위와 같은 구분이 필요하지 않다고 생각하시거나, 다른 의견 있으시면 제안해주세요!
- close #17
=> [FEAT] Home View api 구현 - 팀 정보, 현재 회고 정보

Maddori.Apple-Server/routes/feedbacks/feedbacks.js, Maddori.Apple-Server/routes/reflections/index.js, Maddori.Apple-Server/routes/reflections/reflections.js, Maddori.Apple-Server/routes/teams/index.js, Maddori.Apple-Server/routes/teams/teams.js, Maddori.Apple-Server/routes/users/users.js
response 포맷을 다음과 같이 통일하기로 결정했습니다.
javascript code convention은 다음 규칙을 따르기로 결정했습니다.
https://spice-gym-2c0.notion.site/Javascript-Convention-5babfec9dfc245a5b5efda83c1d99e88
따라서 기존에 작성한 코드를 규칙에 맞게 전체적으로 수정하였습니다.
- response format 변경
```javascript
res.status(201).json({
success: true,
message: '유저 로그인 성공',
datail: createdUser
});
res.status(400).json({
success: false,
message: '유저 로그인 실패',
detail: error.message
});
```
- convention에 맞게 공백 추가 및 제거
- 모듈 이름 보다 명확하게 변경
getTeamInformation -> getCertainTeamDetail
getReflectionInformation -> getCurrentReflectionDetail
19번 브랜치 pull 받으셔서 실행시킨 후, postman에서 userLogin, userJoinTeam, userLeaveTeam, createTeam, getCertainTeamDetail, getTeamMembers, getCurrentReflectionDetail, createFeedback request 보내보시면 정한 response 형식에 맞춰 응답 오는 것 확인하실 수 있습니다!
ex)
제가 놓친 …
=> [CHORE] response 포맷 수정 및 code convention 맞추기

Maddori.Apple-Server/routes/feedbacks/feedbacks.js, Maddori.Apple-Server/routes/feedbacks/index.js, Maddori.Apple-Server/routes/reflections/index.js, Maddori.Apple-Server/routes/reflections/reflections.js
- 나의 회고에서, 현재 팀에서 진행했던 회고 목록 조회 API를 구현했습니다.
- 회고 모음집에서 유저가 받은 특정 타입의 피드백 정보를 조회하는 API를 구현했습니다.
Postman을 이용하여, API Test
- 현재 팀에서 진행했던 회고 목록 가져오기
URI : GET /teams/1/reflections
- 특정 회고에서 유저가 받은 특정 타입의 피드백 정보 모두 가져오기
URI : GET /teams/1/reflections/1/feedbacks/?type=Stop
- 팀이 받은 최근 회고에서 특정 타입의 피드백 정보 모두 가져오기
URI : GET /teams/1/reflections/recent/feedbacks/?type=Stop
- close #29
=> [FEAT] 회고 목록 조회, 특정 타입 피드백 조회 api 구현

Maddori.Apple-Server/routes/reflections/index.js, Maddori.Apple-Server/routes/reflections/reflections.js
홈 뷰에서 아직 회고 정보가 등록되지 않은 상태일 때 리더가 회고 상세 정보를 추가하는 api를 구현했습니다.
- 회고 상세 정보 추가 api 구현
postman에서 updateReflectionDetail 호출하시면 됩니다.
- PATCH api/v1/teams/{team_id}/reflections/{reflection_id}
- request body
```javascript
{
"reflection_name" : "서버 테스트 회고",
"reflection_date" : "2022-11-20"
}
```
- sequelize에서 update 성공 후 해당 레코드를 return하는 방법을 찾지 못해서, update 성공 후에는 pk로 해당 레코드를 다시 찾는 과정을 수행했습니다. 좋은 방법이 있다면 알려주세요!
- 팀의 상태를 검증하는 부분, 유저가 팀의 리더인지 검증하는 부분은 추후 미들웨어 구현 후 추가할 예정입니다.
- 일부분 (회고 이름, 날짜)만 변경하기 때문에 PUT이 아닌 PATCH를 통해 request를 보내도록 구현했습니다.
- close #32
=> [FEAT] Home View api 구현 - 회고 상세 정보 추가

Maddori.Apple-Server/app.js, Maddori.Apple-Server/middlewares/auth.js, Maddori.Apple-Server/routes/feedbacks/index.js, Maddori.Apple-Server/routes/reflections/index.js, Maddori.Apple-Server/routes/teams/index.js
특정 팀 혹은 팀에 속한 회고/피드백/멤버 정보의 조회, 추가, 수정, 삭제를 요청할 때, 요청을 보낸 유저가 해당 팀의 속한 유저인지 검증하는 과정이 필요합니다.
팀의 회고 정보를 등록하거나 진행 중인 회고를 종료하는 과정에서, 요청을 보낸 유저가 해당 팀의 리더인지 검증하는 과정이 필요합니다.
미들웨어는 middlewares 폴더 내에 구현하였으며, 유저의 팀 검증과 리더 검증 모두 요청 권한에 관한 과정이기 때문에 auth 파일의 내부에 구현하였습니다.
- **유저가 요청을 보낸 팀에 속한 멤버인지 검증하는 미들웨어를 구현, 적용하였습니다.**
`/team/{team_id}/` 로 시작하는 end point는 모두 요청을 보낸 유저가 해당 팀에 속한 멤버인지 검증하는 과정을 거쳐야 합니다.
따라서 app.js 파일에서 아래 코드를 추가하여, `/team/{team_id}` 로 시작하는 모든 요청이 유저의 팀 검증 미들웨어를 거치도록 구현하였습니다.
```javascript
// middleware 적용
app.use('/teams/:team_id', userTeamCheck);
```
- **유저가 요청을 보낸 팀의 리더인지 검증하는 미들웨어를 구현, 적용하였습니다.**
유저가 현재 팀의 리더인지 검증하는 과정은 회고 정보 추가와 회고 종료 요청에서만 수행됩니다. 유저의 팀 검증 미들웨어와 달리, 공통적인 end point 형식을 가지는 모든 요청에서 유저의 리더 검증이 필요한 것이 아닙니다. 따라서 해당 미들웨어를 필요로 하는 request를 수행하는 로직에 유저의 리더 검증 함수를 추가하였습니다. …
=> [FEAT] middleware 구현 - 유저의 팀 검증, 리더 검증

Maddori.Apple-Server/routes/feedbacks/feedbacks.js, Maddori.Apple-Server/routes/feedbacks/index.js
MyBox 탭을 눌렀을 때, 팀에서 진행 중인 현재 회고의 피드백 중 요청을 보낸 유저가 특정 멤버에게 작성한 피드백 목록을 가져옵니다.
Continue, Stop 에 따라 구분해서 보여주기 때문에, 피드백 type 별로 피드백 디테일 정보를 담아 response합니다.
1. 팀에서 진행 중인 현재 회고의 id를 가져옵니다.
요청이 `reflections/current/...` 형식으로 들어오지 않는 경우 에러를 발생시킵니다.
2. 받는 유저의 정보를 가져옵니다.
만약 유저 테이블에 받는 유저의 정보가 없다면 에러를 발생시킵니다.
3. 피드백 테이블에서 현재 회고의 id, 보내는 유저의 id, 받는 유저의 id가 일치하는 피드백을 가져옵니다.
4. 피드백의 type(Continue, Stop) 별로 피드백을 분류한 후 response 합니다.
27번 브랜치로 오신 후 postman의 getFromMeToCertainMemberFeedbackAll 요청을 보내시면 됩니다.
header에 반드시 'user_id' 값이 포함되어있어야 합니다.
- 성공했을 경우
- 실패했을 경우
- close #27
=> [FEAT] MyBox View api 구현 - 특정 멤버에게 작성한 피드백 가져오기

Maddori.Apple-Server/routes/feedbacks/feedbacks.js, Maddori.Apple-Server/routes/feedbacks/index.js, Maddori.Apple-Server/routes/reflections/index.js, Maddori.Apple-Server/routes/reflections/reflections.js
- 특정 회고 종료 API 구현
- 회고 상태를 'Done'으로 변경하는 구현
- 특정 팀의 피드백 데이터를 분류해서 조회 API구현
- user id를 기준으로, user의 피드백과 user의 피드백을 제외한 team의 데이터를 분류하여, reponse로 뿌려준다.
- Postman으로 API test
PATCH http://localhost:3000/teams/1/reflections/2/end
- 회고 종료 API
- 피드백 조회 API
- close #35 
- 엔드포인트가 기존에 있던 진행했던 회고 API 구현과 일치하여, 엔드포인트를 임시로
/teams/{team_id}/reflections/{reflection_id}/feedbacks/category/?members={member_id} 으로 수정했습니다. 논의 후 수정이 필요할 것 같습니다.
=> [FEAT] InProgress View - 피드백 정보 분류, 회고 종료 API 구현 

Maddori.Apple-Server/app.js, Maddori.Apple-Server/bin/www, Maddori.Apple-Server/config/config.js, Maddori.Apple-Server/middlewares/auth.js, Maddori.Apple-Server/routes/feedbacks/feedbacks.js, Maddori.Apple-Server/routes/feedbacks/index.js, Maddori.Apple-Server/routes/reflections/index.js, Maddori.Apple-Server/routes/reflections/reflections.js, Maddori.Apple-Server/routes/teams/teams.js, Maddori.Apple-Server/routes/users/index.js, Maddori.Apple-Server/routes/users/users.js
피드백 내용을 수정, 삭제, 등록할 때 회고의 상태가 'Before(회고 진행 이전)'이어야 합니다.
리더가 회고의 정보를 추가할 때 회고의 상태가 'SettingRequired(이름, 날짜 세팅 필요)'이어야 합니다.
원하는 회고 상태에 적합한지 검증하는 미들웨어를 구현하고, 이를 필요로 하는 api에 미들웨어를 적용했습니다.
또한 회고나 피드백에 대한 request를 보낼 때마다 회고 일정이 지났는지를 판단하고, 일정이 지났다면 회고 state를 업데이트 해주는 미들웨어를 구현했습니다.
- 회고 상태 검증 middleware 구현
- createFeedback, updateFeedback, deleteFeedback, updateReflectionDetail API에 미들웨어 적용
미들웨어를 호출할 때 parameter로 요구하는 회고의 state 값('SettingRequired' || 'Before' || 'InProgress' || 'Done') 을 넘겨줍니다.
미들웨어에서는 reflection의 실제 state값과 요구된 state 값을 비교하여, 일치하지 않을 경우 에러를 반환하고 요청 수행을 중단합니다.
- 회고 일정 검증 middleware 구현
회고의 일정과 현재 시간을 비교하고, 일정이 현재 시간 전이라면 회고 state를 Progressing으로 업데이트합니다.
회고 일정 검증과 상태 검증이 모두 이루어지는 경우 일정검증 -> 상태 검증 순으로 이루어집니다.
- createFeedback, updateFeedback, deleteFeedback, updateReflectionDetail …
=> [FEAT] middleware 구현 - 회고의 상태 검증

Maddori.Apple-Server/config/config.js, Maddori.Apple-Server/models/feedback.js, Maddori.Apple-Server/routes/feedbacks/feedbacks.js
- getTeamAndUserFeedback 에러
- getCertainTypeFeedbackAll 에러
- 데이터베이스 timezone 에러 (+9시간이 되어서 시간이 저장됨)
- user- feedback association 수정
연관관계에 한 테이블에 두 개 이상일 경우, association을 정의할 때 as로 테이블 명을 정해줘야 원하는 association을 기준으로 join을 수행할 수 있다고 합니다. 따라서 feedback 테이블의 from_id 는 from_user, to_id 는 to_user로 user 테이블을 연관하게 설정해주었습니다.
- 위 변경사항에 따라 getTeamAndUserFeedback, getCertainTypeFeedbackAll 의 include 부분 수정
상황에 따라 from_user, to_user 정보를 잘 받아올 수 있도록 include 부분을 수정하였습니다.
- 이외에 자잘한 버그를 수정하여 api가 정상 동작하도록 만들었습니다
getTeamAndUserFeedback, getCertainTypeFeedbackAll api  수행
timezone 설정이 local에서는 필요한데, 서버에서는 필요하지 않은 이유를 잘 모르겠네요.. ec2, rds, sequelize에서 각각 어떤 시간 기준을 가지고 있는지 공부가 필요할 것 같습니다.
클라 연결이 바로 진행되기 때문에 리뷰 없이 머지하겠습니다!!
- close #46
=> [BUG] getTeamAndUserFeedback, getCertainTypeFeedbackAll api 버그 수정

Maddori.Apple-Server/routes/teams/teams.js
admin 필드가 boolean이 아닌 1과 0으로 response가 되고 있었습니다. 따라서 이를 boolean 형식으로 변경하였습니다.
- 삼항연산자를 사용한 boolean 형식으로의 변경
- getCertainTeamDetail api 실행
간단한 코드 수정이라 바로 머지하겠습니다!
- close #
=> [CHORE] getCertainTeamDetail admin boolean으로 반환하도록 수정(#48)

Maddori.Apple-Server/routes/teams/index.js, Maddori.Apple-Server/routes/teams/teams.js, Maddori.Apple-Server/routes/users/index.js, Maddori.Apple-Server/routes/users/users.js
'팀 정보 response', '팀 합류' 두 가지로 기존 userJoinTeam api 분리
- 팀 정보 response api 생성 : getCertainTeamName
팀 코드를 query string으로 받아서 코드가 일치하는 팀을 반환하도록 구현했습니다.
- 팀 합류 api 수정 : userJoinTeam
기존에는 body로 코드를 받아서 요청 수행했지만, parameter로 team_id를 받아서 요청 수행하는 방식으로 변경하였습니다.
팀이 존재하지 않는 경우 에러를 반환하고, 이미 유저가 팀에 합류되어있는 경우에도 에러를 반환합니다.
getCertainTeamName, userJoinTeam api를 수행합니다.
api 명세를 참고해주세요.
- userJoinTeam 요청을 보낼 때 body가 없어도 post를 사용했는데, 실제 데이터베이스에서는 새로운 데이터 생성이 이루어지기 때문입니다.
이런 식으로 의미에 맞게 get, post 등의 method를 지정해주는게 맞는 방식인지 잘 모르겠습니다.. 현재는 get method로 userJoinTeam을 수행해도 실행에는 전혀 지장이 없습니다.
- 일단 급한 이슈라 머지는 바로하겠습니다! 나중에 시간 되시면 한 번 읽어봐주세요!
- close #53
=> [FEAT] user join team api 분리

Maddori.Apple-Server/routes/reflections/index.js
- 회고 종료 API에서 리더가 아니어도 회고가 보내짐.
- 리더인 경우
user_id : 1
http://localhost:3000/api/v1/teams/1/reflections/1/end
- 리더가 아닌 경우
user_id: 2
http://localhost:3000/api/v1/teams/1/reflections/1/end
- 회고 상태가 Progressing이 아닌 경우,
user_id : 1
http://localhost:3000/api/v1/teams/1/reflections/1/end
- close #55
=> [CHORE] 회고 종료 API 미들웨어 추가

Maddori.Apple-Server/routes/feedbacks/feedbacks.js
api가 아예 수행이 안되는 오류가 발생했습니다. 이전 수정 사항으로 인한 변동 사항을 제대로 반영하지 못했던 것 같습니다.
user table를 include할 때 to_user라고 명시해줌으로써 문제를 해결했습니다.
updateFeedback 실행
- user 테이블을 include 할 때는 꼭! from_user인지 to_user인지 명시해주세요!
이렇게 하는 이유는, A 테이블에서 두 개 이상의 필드가 B 테이블의 동일 필드를 참조할 때, sequelize는 as를 이용해서 어떤 필드를 기준으로 테이블 조인을 할 지 결정하기 때문입니다.
- close #59
=> [BUG] updateFeedback api 버그 해결

Maddori.Apple-Server/config/config.js
timezone: "+09:00" 설정이 없으면 회고 시간 검증시 시간 비교가 제대로 일어나지 않습니다.
(현재 디비 타임이 UTC 기준이기 때문. 파라미터 그룹 재설정해서 적용하면 인스턴스 재시작 필요하기 때문에 이후 디비 옮길 때 설정 부여. 현재는 임시로 이렇게 해결)
timezone 설정을 추가합니다.
(서버 시간 변경 완료)
추후에 데이터베이스 옮기는 작업이 필요한데(계정 문제로..) 시간 설정은 그 때 진행하고, 지금은 임시로 이렇게 구현하겠습니다.
- close #
=> [FIX] timezone 설정 추가하여 회고 시간 검증 에러 해결

Maddori.Apple-Server/middlewares/auth.js, Maddori.Apple-Server/routes/feedbacks/feedbacks.js, Maddori.Apple-Server/routes/feedbacks/index.js
현재는 회고가 ‘settingRequired’ 상태일 때는 어떤 api이든 요청이 수행됩니다.
Setting Required 상태일 때 수행되면 안되는 api가 존재하기 때문에 미들웨어를 수정합니다.
- reflectionStateCheck에서 두 개의 파라미터를 받습니다.
따라서 required State를 두 개까지 지정할 수 있게 되며, 회고 추가/수정/삭제 api는 required State를 'SettingRequired', 'Befor'로 지정하면 됩니다.
- 미들웨어 적용 사항을 수정합니다.
피드백 생성, 수정, 삭제 api를 수행합니다.
SettingRequired와 Before 상태에 모두 요청이 정상적으로 처리됩니다.
- close #70
=> [BUG] 회고 상태 검증 미들웨어 오류 해결 및 미들웨어 적용 사항 수정

Maddori.Apple-Server/app.js, Maddori.Apple-Server/middlewares/auth.js, Maddori.Apple-Server/models/user.js, Maddori.Apple-Server/models/usertoken.js, Maddori.Apple-Server/package-lock.json, Maddori.Apple-Server/package.json, Maddori.Apple-Server/routes/auth/auth.js, Maddori.Apple-Server/routes/auth/index.js, Maddori.Apple-Server/routes/feedbacks/feedbacks.js, Maddori.Apple-Server/routes/feedbacks/index.js, Maddori.Apple-Server/routes/reflections/index.js, Maddori.Apple-Server/routes/reflections/reflections.js, Maddori.Apple-Server/routes/teams/index.js, Maddori.Apple-Server/routes/teams/teams.js, Maddori.Apple-Server/routes/users/index.js, Maddori.Apple-Server/routes/users/users.js, Maddori.Apple-Server/seeders/testData.js, Maddori.Apple-Server/utils/jwt.util.js
apple login을 구현하였습니다. Contents에 자세한 내용을 적어두었습니다.
1. client에서 request를 보냄
POST /api/v1/login
body에 identity_token 포함
2. appleLogin api 실행
1. identity token 검증 위한 공개키 생성하기
2. 공개키를 사용하여 identity token 검증하기
4. identity token을 decode 하여 유저 정보 가져오기
5. 유저 생성하기 (db 업데이트)
6. user_id(user 테이블의 pk 값), 자체 제작 secret key를 활용해 access token, refresh token 생성하기
7. db에 refresh token 업데이트 하기
8. access token, refresh token, 유저 정보 응답하기
1. client에서 request를 보냄
header에 access_token, refresh_token 포함
2. userCheck middleware 실행
1. secret key를 활용해 access token 검증하기
1. 토큰이 유효할 경우
access_token을 decode하여 user_id 값 구하기
request.user_id에 user_id 값 적용하여, 다음 미들웨어 or 핸들러에서 요청을 보낸 user의 user_id 값을 사용할 수 있도록 하기
2. 토큰이 유효하지 않을 경우 (시간 만료 등)         
'유저 검증 실패’ 에러 반환
2. 토큰이 유효할 경우 api에 따른 요청 수행, 응답
- 검증 프로세스
1. …
=> [FEAT] apple login 구현

Maddori.Apple-Server/middlewares/auth.js, Maddori.Apple-Server/routes/feedbacks/feedbacks.js, Maddori.Apple-Server/routes/feedbacks/index.js
기존에는 reflectionStateCheck에서 최대 두 개까지의 상태만 받아서, 회고가 해당 상태를 만족하는지 검증했습니다.
하지만 getFromMeToCertainMemberFeedbackAll에서 3개 중 하나의 상태에 만족하는지를 판단해야 하기 때문에 reflectionStateCheck 미들웨어를 수정합니다.
reflectionStateCheck에서 배열 인자를 받는 형식으로 수정합니다.
getFromMeToCertainMemberFeedbackAll 수행.
- close #78
=> [FIX] reflectionStateCheck 배열 인자 받아서 실행하도록 수정

Maddori.Apple-Server/routes/reflections/reflections.js
홈 화면에서 키워드 리스트를 역순으로 받아와야 합니다.
키워드 리스트를 불러오는 과정에서 order 설정을 추가하였습니다.
id 기준으로 내림차순 나열하였으며, timestamp 필드가 없기 때문에 id를 정렬의 기준으로 사용하였습니다.
getCurrentReflectionDetail 실행
추후 timestamp 를 추가하여 timestamp 기준으로 정렬하는 것이 좋을 것 같습니다.
- close #
=> [ADD] getCurrentReflectionDetail 키워드 리스트 역순 설정 추가(#48)

Maddori.Apple-Server/routes/feedbacks/feedbacks.js
updateFeedback, getCertainTypeFeedbackAll  api 수행시 이전과 다른 response 형식으로 응답됩니다.
apple login의 추가로 인해 from_user 부분에 email, sub 값이 모두 포함되어 응답이 보내짐.
updateFeedback, getCertainTypeFeedbackAll 의 from_user 테이블을 조인하는 과정에서, Id, username 정보만 가져올 수 있도록 코드를 추가합니다.
updateFeedback, getCertainTypeFeedbackAll 실행
- close #80
=> [CHORE] response 형식 수정

Maddori.Apple-Server/routes/auth/auth.js, Maddori.Apple-Server/routes/auth/index.js
회원 탈퇴 기능이 필요해짐으로써 회원 정보 삭제를 진행하는 회원 탈퇴 api 구현
- 회원 탈퇴 api 구현
token을 활용한 유저 정보 파악 이후 user 테이블에서 해당 user의 정보 삭제하기
- 회원의 정보(username, email, refresh_token), 회원과 관련된 정보(팀과의 관계, 받았던 피드백) 삭제 확인
- singOut api 실행 (delete /api/v1/login/signout)
- 유저 정보 삭제 성공
- 유저 정보 삭제 실패
/login/signout 이라는 URI가 어색해서, 추후에 /signout으로 바꿔야 할 것 같습니다.
현재는 auth 로 login, signout을 함께 묶느라 /login/signout 형태로 URI 설계하였습니다.
ASAP이기 때문에 코드 리뷰 없이 머지합니다!
- close #87
=> [FEAT] 회원 탈퇴 api 구현

Maddori.Apple-Server/middlewares/auth.js, Maddori.Apple-Server/routes/reflections/reflections.js
쇼케이스 부스 진행시 회고를 바로 진행할 수 있게 일정을 현재로(분까지 일치하는 시간) 등록할 수 있어야합니다. (클라이언트에서는 초를 지정할 수 없기 때문에 항상 ??시 ??분 으로 등록 시간 값이 들어옵니다)
또한 회고를 바로 시작하고 싶을 때 일정을 현재로 등록해야하기 때문에 위 기능을 추가합니다.
- 기존 구현 방법
기존에는 `등록시간<현재시간(초 포함)` 일 때만 회고 일정 등록이 가능하도록 해주었기 때문에 등록시간이 13:00일 경우 현재 시간이 13:00:01 초라면 회고 일정이 등록되지 못합니다. 따라서 회고를 바로 시작하고 싶다면 항상 1분 뒤로 회고 일정을 등록해야 합니다.
- 회고 일정 등록(updateReflectionDetail) api 수정
현재 시간에서 초 단위를 제거하고 요청으로 들어오는 회고 일정 시간 값과 비교를 진행합니다.
회고 일정 요청 값 < 현재 시간 값 (분 단위) 를 만족한다면 회고 일정이 성공적으로 등록될 것입니다.
- 회고 시간 검증(reflectionTimeCheck) api 수정
현재 시간과 회고 일정이 동일할 때도 회고 상태가 바뀌도록 수정
updateReflectionDetail api 수행
- 현재 시간과 동일하게 회고 일정을 등록하면, 메인 화면에서 다시 getCurrentReflectionDetail이 수행되며 reflectionTimeCheck 미들웨어가 수행되어 회고 상태가 Progressing으로 바뀌게 됩니다.
현재 시간으로 지정해도 회고 일정이 정상적으로 등록되는 결과
- close #97
=> [FEAT] reflection 일정 현재(분 단위)로 등록할 수 있도록 수정
